### ISSUE TITLE
Relative paths in test .yaml files

### ISSUE THREAD

**Issue by Falcury** [Sbrussee/PathBench-MIL#5]
Maybe better to use relative paths here (with path relative to the yaml file), so that the tests can be run more easily by others?

https://github.com/Sbrussee/PathBench-MIL/blob/4ac546595c8fab185f86b36000885fb0d522294b/pathbench/test/survival_test_conf.yaml#L3

And maybe similar for the pretrained weights directory?
`weights_dir` and `hf_token` could also maybe inherit from a user-specific configuration file? May also be useful to avoid exposing HF tokens while still facilitating the exchange or publishing of the .yaml files without needing to modify them.
https://github.com/Sbrussee/PathBench-MIL/blob/4ac546595c8fab185f86b36000885fb0d522294b/pathbench/test/regression_test_conf.yaml#L80-L81

**Comment by Sbrussee** [comment]
Weights directory is locally defined now, with a pretrained_weights directory is added to the PathBench repository as a default directory for model weights
